version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - shared_data:/app/share

  backend:
    image: webdevops/php-nginx-dev:8.2
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - ./backend/:/app
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      XDEBUG_CLIENT_HOST: host.docker.internal
      PHP_DATE_TIMEZONE: Europe/Berlin



volumes:
  shared_data:
