version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app



volumes:
  shared_data:
